### ISSUE TITLE
Directory containing expert trajectories is missing (expert_logs)

### ISSUE THREAD

**Issue by brokenBrain** [illidanlab/opolo-code#1]
I am unable to find the directory containing expert trajectories. It appears to be missing. Can you update the repo with the expert trajectories? Or let me know how the expert trajectories were generated? I need to know whether you all included the 'setup' phase of the demonstration. I.e. for the HalfCheetah demonstration, does the demonstration only have the agent running? Or does the demonstration also include the agent starting to run?

**Comment by zhuangdizhu** [comment]
Hi, it is already located at opolo-code/opolo-baselines/expert_logs

**Comment by brokenBrain** [comment]
Got it. I think I got confused by a different branch. Thanks for the quick reply!
